### PR TITLE
Add Ollama provider

### PR DESCRIPTION
**Pull request by tomaslucas**
This feature add an Ollama provider.

### CODE REVIEW

**Comment by ncoop57** [comment]
Hey @tomaslucas, thanks so much for the PR! However, I think this functionality belongs actually in cosette. If we allow users of cosette to specify the base url we get all the niceties of any model provider that uses openai's protocol out of the box. That way we don't need to add support for others by create separate clients to how you did here with Ollama. Do you think you could look into what it would take to get this working in cosette? Happy to offer advice and assistance

**Comment by tomaslucas** [comment]
No problem. Thank you, @ncoop57 , for your answer.

**Comment by tomaslucas** [comment]
> Hey @tomaslucas wanted to let you know that made a change to now allow this in a bit more general way to shell sage. You can now pass in a base url and api key directly or via the config file

I tried but it doesn't work in my Linux Ubuntu 22.04 installation:

shell_sage % uv tool list
ruff v0.6.2
- ruff
shell-sage v0.0.5
- ssage

shell_sage % ssage --verbosity 1 --provider openai --model gemma2:2b --base_url http://localhost:11434/v1 --api_key ollama "how shell_sage works"
usage: ssage [-h] [--pid PID] [--skip_system] [--history_lines HISTORY_LINES] [--s] [--provider PROVIDER] [--model MODEL]
             [--code_theme CODE_THEME] [--code_lexer CODE_LEXER] [--verbosity VERBOSITY]
             query [query ...]
ssage: error: unrecognized arguments: --base_url --api_key ollama how shell_sage works
shell_sage % ssage --provider openai --model gemma2:2b --base_url http://localhost:11434/v1 --api_key ollama what is rsync?
zsh: no matches found: rsync?
shell_sage % ssage --provider openai --model gemma2:2b --base_url http://localhost:11434/v1 --api_key ollama "what is rsync?"
usage: ssage [-h] [--pid PID] [--skip_system] [--history_lines HISTORY_LINES] [--s] [--provider PROVIDER] [--model MODEL]
             [--code_theme CODE_THEME] [--code_lexer CODE_LEXER] [--verbosity VERBOSITY]
             query [query ...]
ssage: error: unrecognized arguments: --base_url --api_key ollama what is rsync?
shell_sage % ssage --provider openai --model gemma2:2b --base_url http://localhost:11434/v1 --api_key ollama "what is rsync" 
usage: ssage [-h] [--pid PID] [--skip_system] [--history_lines HISTORY_LINES] [--s] [--provider PROVIDER] [--model MODEL]
             [--code_theme CODE_THEME] [--code_lexer CODE_LEXER] [--verbosity VERBOSITY]
             query [query ...]
ssage: error: unrecognized arguments: --base_url --api_key ollama what is rsync
shell_sage %

If I call directly to Ollama it works.

shell_sage % docker exec -it ollama ollama run gemma2:2b
>>> "what is rsync?"
Rsync (rsync -- recursive synchronization) is a powerful and versatile command-line tool used for **efficient file syncing, 
especially between computers over the network.**  

Here's a breakdown:

**How it works:**

* **Synchronization:**  Rsync compares files at specific points in time to see what needs to be updated or transferred.
* **Recurrent Updates:** It can also be set up to automatically synchronize your files periodically, keeping things consistent even 
when you're offline or working on different locations. 
* **Efficiency:** This tool is designed for speed and efficiency, especially when dealing with large amounts of data like photos, 
videos, or code repositories.

**Key Features:**

* **Remote Syncing:**  Rsync can sync files between local machine and remote servers (e.g., Dropbox, Google Drive, Amazon S3), as 
well as other networks.
* **Selective Synchronization:** Choose specific files to transfer or synchronize entire directories based on a variety of criteria 
(like file modification dates).
* **Compression:** Rsync compresses data to reduce transfer speeds and save disk space. 
* **Resync:** Automatically detect changes and resync the remote files when your source files are updated, ensuring everything 
stays in sync.
* **File Changes:** Tracks which files changed since the last synchronization.  

**Common Use Cases:**

* **Backups:** Create consistent backups of important data across multiple computers or servers.
* **Data Synchronization:** Keep local and remote server data synchronized for collaboration, version control, etc. 
* **Cloud Storage Management:** Manage cloud storage accounts efficiently by automating sync operations.


**Learning Resources:**

* **Rsync Documentation (rsync man page):** https://man7.org/linux/man-pages/man1/rsync.1.html
* **Online Tutorials and Articles:**  Plenty of resources available on websites like Linux Foundation, tutorialspoint, etc.


Let me know if you'd like more detail about specific features, options for use, or a comparison to other file synchronization 
tools! 


>>> Send a message (/? for help)

When I have a little time I will look into it.
Thanks.

**Comment by ncoop57** [comment]
@tomaslucas interesting! could you open up an issue and also provide your shell_sage config file in it? I have a sneaking suspicion I know why this isn't working

**Pull request closed without merging**
